# The JDBC URL for the MySQL database connection
spring.datasource.url=${{ MySQL.MYSQL_URL }}

# The username for the database
spring.datasource.username=${{ MySQL.MYSQLUSER }}

# The password for the database
spring.datasource.password=${{ MySQL.MYSQLPASSWORD }}

# The driver class name for MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver